translate #1285
playframework-ja/translation-project pull request #1415
Opened 2017-06-06 12:31 UTC by 12345

2.3.xで翻訳されている箇所はそれらをベースにしていますが、後から全体的に見直して部分的にちょこちょこいじっています。

2017-06-11 08:57 UTC, garbagetown commented
ありがとうございます！

章タイトルから見直して頂いているので、マージ前に意識合わせさせてください。2.3.x 以前にバックポートする必要も出てくるのかなーと思いました (って言うか 2.3.x は未訳箇所が放置されてますね... 😓 )

これまで `compose` は `合成` と訳してきましたが、今回 `構成` に変更頂いたのはどのような理由からでしょう？

2017-06-12 01:38 UTC, 12345 commented
この章はアクションのいろいろな実装方法を紹介していると理解しましたので、`合成`というよりは`構成`や`組み立て`のほうが意味合いとしては合っているのかな、と考えました。

また、2.3.xでの訳の本文中に、`mix in`や`mixed in`の訳としても`合成`が出てきますが、これはいろいろな`action compsition`の中の１つのやり方のことを指していると考えました。だとするとタイトルのほうは`合成`でない表現のほうが紛らわしくなくて良いと思いました。（といいつつ、`mix in`ほうも表現を変えちゃってますが・・・）

あと、`構成`と`組み立て`では`組み立て`のほうがより意味合いが伝わりやすいかなと思いましたが、本文中にも`action composition`の表現が出てくるので、そこでの字面の収まりの良さを考え、最終的に`構成`としました。

説明もなしにいきなり変えてしまってすみません！m(_ _)m
よろしくお願いします。

2017-06-13 02:07 UTC, garbagetown commented
変更理由について了解しました！タイトルを見直す方向で確認させて頂きます  :relieved:

2017-06-13 03:38 UTC, 12345 commented
お手数おかけします。よろしくお願いします！

2017-06-14 18:48 UTC, garbagetown requested changes
数点コメントしました！ご確認お願いします :-)

2017-06-14 18:48 UTC, garbagetown commented on manual/working/scalaGuide/main/http/ScalaActionsComposition.md
> +Play には [[グローバルなフィルター API | ScalaHttpFilters]] も用意されていて、グローバルなクロスカッティングの問題に役立ちます。
「クロスカッティングの問題」が直感的でないように感じました。

元の訳も活かして「Play は全体的な横断的関心事に便利な [[グローバルなフィルター API | ScalaHttpFilters]] も提供しています。」 くらいでいかがでしょう？

2017-06-14 18:48 UTC, garbagetown commented on manual/working/scalaGuide/main/http/ScalaActionsComposition.md
> +次に、そのアイテムを調べ、エラー (`Left`) または新しい `ItemRequest` (`Right`) を返すアクションリファイナーを作成します。このアクションリファイナーは、アイテムの ID を取得するメソッド内で定義されています。
「アクションリファイナー」をどうしましょうね。
原文が「ActionRefiner」ならカタカナにせず、そのまま「ActionRefiner」でよいと思いますが、原文が「action refiner」なので悩む...

「action builder」などの例に倣って、ひとまずカタカナのままにしましょうか。

2017-06-14 18:48 UTC, garbagetown commented on manual/working/scalaGuide/main/http/ScalaActionsComposition.md
> +次に、`Item` 型のオブジェクトで動作する REST API について考えてみましょう。`/item/:itemId` パスの下には多くのルートがあり、そして各々アイテムを調べる必要があります。この場合、このロジックをアクション関数に入れると便利です。
「In this case, 」より前は元の訳で特に違和感ないように思います。

「Item 型というオブジェクトについて動作する REST API について考えてみましょう。 /item/:itemId というパスの下に多くのルートがあり、それらのルートでは　Item を見つける必要があるとします。」でいかがですか？

2017-06-14 18:48 UTC, garbagetown commented on manual/working/scalaGuide/main/http/ScalaActionsComposition.md
> +アクションを構築するためのこれらのメソッドは、実際は [`ActionBuilder`](api/scala/play/api/mvc/ActionBuilder.html) と呼ばれるトレイトに全て定義されています。　また、 これまでに定義してきた [`Action`](api/scala/play/api/mvc/Action$.html) オブジェクトはこのトレイトの単なるインスタンスです
「独自の `ActionBuilder` を実装することで、再利用可能なアクションスタックを宣言、作成してアクションを構築することができます。」は

「独自の `ActionBuilder` を実装することで、アクションを作るために使用できる、再利用可能なアクションスタックを宣言することができます。」でしょうか。

2017-06-16 01:17 UTC, 12345 commented
ご指摘いただいた内容で修正してみました！ご確認お願いします。

2017-06-16 01:21 UTC, 12345 commented on manual/working/scalaGuide/main/http/ScalaActionsComposition.md
> +次に、そのアイテムを調べ、エラー (`Left`) または新しい `ItemRequest` (`Right`) を返すアクションリファイナーを作成します。このアクションリファイナーは、アイテムの ID を取得するメソッド内で定義されています。
了解しました！

2017-06-16 01:27 UTC, garbagetown approved these changes

2017-06-16 01:28 UTC, merged

2017-06-16 01:30 UTC, garbagetown commented
ご対応ありがとうございました！2.3.x 以前へのバックポートは私のほうで対応いたします :blush:

2017-06-16 01:37 UTC, 12345 commented
ご確認ありがとうございます！
バックポートのご対応よろしくお願いいたします。m(_ _)m