translate #1278
playframework-ja/translation-project pull request #1425
Opened 2017-07-03 11:39 UTC by 12345

2.3.xの流用＋一部修正＋未訳箇所の翻訳です。

2017-07-06 09:06 UTC, garbagetown commented
対応が遅れており申し訳ありません。次週07/11火曜日に確認させて頂ければと思います😣
On Mon, Jul 3, 2017 at 20:39 12345 <notifications@github.com> wrote:

> 2.3.xの流用＋一部修正＋未訳箇所の翻訳です。
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/playframework-ja/translation-project/pull/1425
> Commit Summary
>
>    - translate #1278 - 2.3.xの流用分
>    - translate #1278 - 英単語のままの語の翻訳
>    - translate #1278 - 表現の修正など
>    - translate #1278 - 未訳箇所の翻訳
>
> File Changes
>
>    - *M* manual/working/scalaGuide/main/async/ScalaWebSockets.md
>    <https://github.com/playframework-ja/translation-project/pull/1425/files#diff-0>
>    (101)
>
> Patch Links:
>
>    -
>    https://github.com/playframework-ja/translation-project/pull/1425.patch
>    -
>    https://github.com/playframework-ja/translation-project/pull/1425.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/playframework-ja/translation-project/pull/1425>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAExKRbBfs2RmVJ_-hlpqNqB9R2-moOxks5sKNL-gaJpZM4OMLUY>
> .
>

2017-07-06 11:10 UTC, 12345 commented
了解です！
こちらはいつでも大丈夫ですので、気長にお待ちしております！:smile:

2017-07-12 13:15 UTC, garbagetown requested changes
対応が遅くなり申し訳ありません！確認して数点コメントしました。ご確認ください 😊

2017-07-12 13:15 UTC, garbagetown commented on manual/working/scalaGuide/main/async/ScalaWebSockets.md
> +最新の HTML5 に準拠した Web ブラウザは、JavaScript WebSocket API を介して WebSocket をネイティブにサポートします。しかし、WebSocket は Web ブラウザだけで使用されているだけでなく、WebSocket クライアントライブラリが数多くあるため、サーバー同士でやりとりすることができ、WebSocket を使用するネイティブのモバイルアプリも
「WebSocket クライアントライブラリが数多くあるため、サーバー同士でやりとりすることができ、WebSocket を使用するネイティブのモバイルアプリもあります。」
ですが、`allowing for example ...` は `例えば〜することができる` かなと思いますので、
「例えばサーバ同士で会話したり、ネイティブのモバイルアプリで WebSocket を使ったりすることのできる WebSocket クライアントライブラリがたくさんあります。」などはいかがでしょうか。

2017-07-12 13:15 UTC, garbagetown commented on manual/working/scalaGuide/main/async/ScalaWebSockets.md
> +最新の HTML5 に準拠した Web ブラウザは、JavaScript WebSocket API を介して WebSocket をネイティブにサポートします。しかし、WebSocket は Web ブラウザだけで使用されているだけでなく、WebSocket クライアントライブラリが数多くあるため、サーバー同士でやりとりすることができ、WebSocket を使用するネイティブのモバイルアプリも
「これらのコンテキストで WebSocket を使用すると、」
ですが、`Using WebSockets in these contexts` が主語だと思いますので、
「このような状況において WebSocket を使用することには」などいかがでしょうか。

2017-07-12 13:15 UTC, garbagetown commented on manual/working/scalaGuide/main/async/ScalaWebSockets.md
> +Play には、WebSocket を処理するための2つの異なる組み込みのメカニズムが用意されています。一つ目のメカニズムはアクターを使用し、二つ目はイテレートを使用します。これらの両方のメカニズムには、[WebSocket](api/scala/play/api/mvc/WebSocket$.html) で提供されるビルダーを使用してアクセスできます。
Iteratee をイテレートと訳すのは...うーん、どうなんでしょう？ 😅 
間違いではないですが、あまり見掛けないような。
とは言え大文字で始まっていないので訳したくなりますね。。。いったん「イテレート」にしてみましょうか。

2017-07-12 13:15 UTC, garbagetown commented on manual/working/scalaGuide/main/async/ScalaWebSockets.md
> +WebSocket が閉じると、Playは自動的にアクターを停止します。つまり、WebSocket が消費した可能性のあるリソースをすべて綺麗に片付ける処理を行うような、アクターの `postStop` メソッドを実装することで、この状況を処理することができます。例を示します。
「綺麗に」はなくてもいいかなーと思いました。

2017-07-12 13:15 UTC, garbagetown commented on manual/working/scalaGuide/main/async/ScalaWebSockets.md
> +クライアントから受信したメッセージはすべてアクターに送信され、Play から提供されたアクターに送信されたメッセージはすべてクライアントに送信されます。アクターは、単にクライアントから受け取ったすべてのメッセージを `I received your message: ` を先頭に付けて送るだけです。
「アクターは、単にクライアントから受け取った〜」
ですが、`The actor above simply sends...` は上記例のアクターを指しているので、
「上記のアクターは、単にクライアントから受け取った〜」としてはいかがでしょう。

2017-07-12 13:15 UTC, garbagetown commented on manual/working/scalaGuide/main/async/ScalaWebSockets.md
> +場合によっては、WebSocket リクエストを拒否することもできます。たとえば、WebSocket に接続するためにユーザーを認証する必要がある場合、または WebSocket がパスの中で ID を通過させるようなリソースに関連付けられている場合で、その ID を持つリソースが存在しない場合などです。Play はこれに対処するための `tryAcceptWithActor` を提供し、結果(
「場合によっては、WebSocket リクエストを拒否することもできます。」ですが、
`you may wish...` なので、「拒否したい場合もあるでしょう」くらいのニュアンスかと思います。また、原文も一文なので、やや長くなりますが
「例えば WebSocket に接続するためにユーザーを認証する必要がある場合、または WebSocket がパスの中で ID を通過させるようなリソースに関連付けられている場合で、その ID を持つリソースが存在しない場合など、WebSocket リクエストを拒否したい場合もあるでしょう」などはいかがですか？

2017-07-12 13:15 UTC, garbagetown commented on manual/working/scalaGuide/main/async/ScalaWebSockets.md
> +これまでのところ、`String` フレームの処理しか見ていませんでした。Play には  `Array [Byte]` フレーム用のハンドラと `String` フレームから解析された ` JsValue` メッセージが組み込まれています。これらを型パラメータとして WebSocket 作成メソッドに渡すことができます。たとえば、次のようにします。
`handlers for` は `Array[Byte]` と `JsValue` に係っていると思います。
「Play には  `Array [Byte]` フレームと、`String` フレームから解析された ` JsValue` メッセージ用のハンドラが組み込まれています。」かなーと思いました。

2017-07-12 13:15 UTC, garbagetown commented on manual/working/scalaGuide/main/async/ScalaWebSockets.md
> +- `out` チャンネルは、Web クライアントに送信されるメッセージを生成する `Enumerator[A]` チャネルです。`EOF` を送信することで、サーバー側の接続を閉じることができます。
「`Enumerator[A]` チャネルです。」はシンプルに「`Enumerator[A]` です。」でいいかなと思いました。

2017-07-13 12:52 UTC, 12345 commented
ご指摘いただいた内容で修正しました！ご確認をお願いします。

なお、次は「テンプレートエンジン」の章をやろうと思ったのですが、2.4.xには該当ディレクトリ(scalaGuide/templates)が見当たりません。実際に表示されている2.4.xのテンプレートエンジンの章はどこにあるファイルが使われているのでしょうか？

2017-07-13 12:52 UTC, 12345 commented on manual/working/scalaGuide/main/async/ScalaWebSockets.md
> +Play には、WebSocket を処理するための2つの異なる組み込みのメカニズムが用意されています。一つ目のメカニズムはアクターを使用し、二つ目はイテレートを使用します。これらの両方のメカニズムには、[WebSocket](api/scala/play/api/mvc/WebSocket$.html) で提供されるビルダーを使用してアクセスできます。
了解です！

2017-07-14 04:42 UTC, garbagetown commented
テンプレートのドキュメントはTwirlのものを読み込んでいるようです。
https://github.com/playframework-ja/translation-project/issues/1322#issuecomment-185525830

翻訳プロジェクトとしてどのようにリポジトリ、ブランチを管理すべきなのか把握できていません。この三連休を目処に確認しますので、取り急ぎ翻訳だけ進めていただければと思います。

2017-07-14 04:46 UTC, merged

2017-07-14 08:48 UTC, 12345 commented
了解いたしました。ご確認よろしくお願いいたします。お手数をおかけします。m(_ _)m

雰囲気的には、
2.4.x(ja)：無いっ！→2.4.x(en)：無いっ！→2.3.x(en)：あった！これ表示！
みたいな感じなんですかね・・・

とりあえずテンプレートエンジンの章は置いておいて、他の章の翻訳に着手したいと思います！