translate #1283
playframework-ja/translation-project pull request #1426
Opened 2017-07-18 15:09 UTC by 12345

2.3.xは翻訳箇所が局所的だったのでタイトルのみ流用し、本文はすべて新規に翻訳しました。

2017-07-21 12:36 UTC, garbagetown commented
対応が遅れており申し訳ございません。この週末に確認させてください :persevere:

2017-07-21 12:52 UTC, 12345 commented
了解です！よろしくお願いします！:smile:
急いでおりませんので、いつでも大丈夫です！

2017-07-31 11:27 UTC, garbagetown requested changes
大作の翻訳ありがとうございます！確認して数点コメントしました。ご確認よろしくお願いいたします :-)

2017-07-31 11:27 UTC, garbagetown commented on manual/working/scalaGuide/main/forms/ScalaForms.md
> +* アクション内のフォームを検証し、
アクション内 `で` のほうがよろしいかと！

2017-07-31 11:27 UTC, garbagetown commented on manual/working/scalaGuide/main/forms/ScalaForms.md
> +最終的には次のようになります。
"最終的な結果は次のようになります。" はいかがでしょうか？

2017-07-31 11:27 UTC, garbagetown commented on manual/working/scalaGuide/main/forms/ScalaForms.md
> +この [Forms](api/scala/play/api/data/Forms$.html) には、[`mapping`](api/scala/play/api/data/Forms$.html#mapping%5BR%2CA1%5D\(\(String%2CMapping%5BA1%5D\)\)\(\(A1\)%E2%87%92R\)\(\(R\)%E2%87%92Option%5BA1%5
`This method takes the names and ...` 以降の訳が抜けているようです :relieved:

2017-07-31 11:27 UTC, garbagetown commented on manual/working/scalaGuide/main/forms/ScalaForms.md
> +* **フォーム専用のケースクラスは強力です。** タプルを使用するのは便利ですが、カスタムの apply や unapply メソッドは許可されず、含まれるデータの参照は、項数 (`_1`, `_2` など) によってのみ可能です。
arity の訳はむずかしいですね。
「含まれるデータは、(`_1`, `_2` などの) 変数によってのみ参照できます。」などはいかがでしょう？

2017-07-31 11:27 UTC, garbagetown commented on manual/working/scalaGuide/main/forms/ScalaForms.md
> +`text` 制約は、空文字列が有効であるとみなします。つまり、ここでは `name` はエラーなしで空にできることを意味します。これは望む形ではありません。`name` が適切な値を持つことを保証する方法は `nonEmptyText` 制約を使うことです。
「つまり、ここでは `name` はエラーなしで空にできることを意味します。これは望む形ではありません。」は、そこまで長くないので、原文どおり一文でよいと思います。
「これは `name` をエラーなしで空にできることを意味しますが、これは望ましいものではありません。」などはいかがでしょう？

2017-07-31 11:27 UTC, garbagetown commented on manual/working/scalaGuide/main/forms/ScalaForms.md
> +`text` 制約は、空文字列が有効であるとみなします。つまり、ここでは `name` はエラーなしで空にできることを意味します。これは望む形ではありません。`name` が適切な値を持つことを保証する方法は `nonEmptyText` 制約を使うことです。
「`name` が適切な値を持つことを保証する方法は `nonEmptyText` 制約を使うことです。」が、やや直訳に感じました。

「`name` が適切な値を持つことを保証するには `nonEmptyText` 制約を使います。」などはいかがでしょうか？

2017-07-31 11:27 UTC, garbagetown commented on manual/working/scalaGuide/main/forms/ScalaForms.md
> +* **フォーム専用のケースクラスは便利です。** ケースクラスは、データのシンプルなコンテナになるように設計されており、`Form` 機能と自然にマッチした機能をすぐに提供します。
`and provide out of the box features ` は「デフォルトで提供している」のような意味なので、「すぐに提供します」は少々ニュアンスが異なるのかなと思いました。
「デフォルトで提供します」でどうでしょう？

2017-07-31 11:27 UTC, garbagetown commented on manual/working/scalaGuide/main/forms/ScalaForms.md
> +すぐに使用できる制約は [Forms object](api/scala/play/api/data/Forms$.html) に定義されています。
ここも「デフォルトで使える制約は」でよいと思います :-)

2017-07-31 11:27 UTC, garbagetown commented on manual/working/scalaGuide/main/forms/ScalaForms.md
> +成功の場合、ビューテンプレートをレンダリングする代わりに `routes.Application.home` へのルートを持つ `Redirect` をここに送ります。このパターンは [Redirect after POST](https://en.wikipedia.org/wiki/Post/Redirect/Get) と呼ばれ、重複したフォームの送信を防ぐ優れた方法です。
`here` は無理に訳さなくてもいいかもですね。また、「重複したフォームの送信」は、「重複した」が「フォーム」に掛かるようにも読んでしまう人もいるかもと思いました。

「成功の場合、ビューテンプレートをレンダリングする代わりに `routes.Application.home` へのルートを持つ `Redirect` を送ります。(略)フォームの重複送信を防ぐ優れた方法です。」 などはいかがでしょうか？

2017-07-31 11:27 UTC, garbagetown commented on manual/working/scalaGuide/main/forms/ScalaForms.md
> +最初に、[form タグ](api/scala/views/html/helper/form$.html) を作成することができます。これは単純なビューヘルパーで、[form タグ](http://www.w3.org/TR/html5/forms.html#the-form-element) を作成し、通るルートの逆に従って `action` と `method` タグのパラメータを設定します
`according to the reverse route you pass in` は「引数に渡したリバースルートに従って」でよいと思います。

routes ファイルはルートパス -> アクションの順に設定されており、通常はリクエストパスからアクションを解決するために用いられますが、form タグを生成する場合などはアクションからパスを逆引きし、これをリバースルートと呼ぶことがあります。

2017-07-31 11:27 UTC, garbagetown commented on manual/working/scalaGuide/main/forms/ScalaForms.md
> +* [`input`](api/scala/views/html/helper/input$.html): 一般的な入力要素 (明示的な引数が必要) をレンダリングします。
`generic` は「汎用的な」のほうがよろしいかと :-)

2017-07-31 11:27 UTC, garbagetown commented on manual/working/scalaGuide/main/forms/ScalaForms.md
> +上記の一般的な `input` ヘルパーは、あなたが望む HTML の結果をコード化することを可能にします。
こちらも「汎用的な」でいかがでしょう？

2017-07-31 11:27 UTC, garbagetown commented on manual/working/scalaGuide/main/forms/ScalaForms.md
> +タプルを使用すると、特に項数が少ないタプルの場合、ケースクラスを定義するよりも便利になります。
あー、ここの arity は "項数" が適切ですね。先の arity もこことバランスを取って "項数" でもいいかもしれません。

2017-07-31 11:27 UTC, garbagetown commented on manual/working/scalaGuide/main/forms/ScalaForms.md
> +一般的なデータ編集において、フォームに既存の値を設定したくなる場合があります。
`typically for editing data` は「典型的にはデータの編集」なので、やや意訳して
「典型的にはデータを編集する場合など、フォームに既存の値を設定したくなる場合があります。」などはいかがでしょう？

2017-07-31 13:59 UTC, 12345 commented on manual/working/scalaGuide/main/forms/ScalaForms.md
> +タプルを使用すると、特に項数が少ないタプルの場合、ケースクラスを定義するよりも便利になります。
了解です！

2017-07-31 14:03 UTC, 12345 commented
多くのご指摘ありがとうございます！
修正しましたのでご確認をお願いします。

2017-08-01 03:27 UTC, garbagetown commented
ご対応ありがとうございました。確認しました :smiley:

2017-08-01 03:27 UTC, merged