translate #1281
playframework-ja/translation-project pull request #1429
Opened 2017-07-21 12:36 UTC by 12345

すべて新規翻訳です。

2017-07-26 22:07 UTC, garbagetown requested changes
ありがとうございます！数点コメントしましたので、ご確認ください。

この部分、2.2.x からスカっと抜けてますね...こちらでバックポートしておきます。

2017-07-26 22:07 UTC, garbagetown commented on manual/working/scalaGuide/main/forms/ScalaCustomFieldConstructors.md
> +フィールドレンダリングは `<input>` タグで構成するだけでなく、フィールドを修飾するためにCSSフレームワークで使用される `<label>` や他のタグも必要です。
文脈から察するに、原文の意図としては `used by your CSS framework` は `possibly other tags` だけに係り、`<label>` には係らないのかな？と思いました。

「フィールドのレンダリングは `<input>` タグだけから構成されるものではなく、`<label>` や、おそらくフィールドを修飾する CSS フレームワーク が使用するその他のタグも必要になります。」などはいかがでしょう？

2017-07-26 22:07 UTC, garbagetown commented on manual/working/scalaGuide/main/forms/ScalaCustomFieldConstructors.md
> +すべての入力ヘルパーは、この役割を担う暗黙の [`FieldConstructor`](api/scala/views/html/helper/FieldConstructor.html) を使用します。[デフォルトフィールドコンストラクタ](api/scala/views/html/helper/defaultFieldConstructor$.html) (スコープ内で利用可能な他のフィール
「デフォルトフィールドコンストラクタ」とつなげて表記すると固有名詞のように見えるかも？と思いました。
次の段落と合わせて「デフォルトのフィールドコンストラクタ」としてはいかがでしょう？

2017-07-26 22:07 UTC, garbagetown commented on manual/working/scalaGuide/main/forms/ScalaCustomFieldConstructors.md
> +これをフォームヘルパーで使えるようにするには、テンプレートでインポートします。
段落が分かれていますが、前後の段落と内容がつながっているように読めるので、
「そして、これをフォームヘルパーで使えるようにするために、テンプレート内にインポートします。」
とするのはいかがでしょう？

2017-07-26 22:07 UTC, garbagetown commented on manual/working/scalaGuide/main/forms/ScalaCustomFieldConstructors.md
> +次に、フィールドコンストラクターを使用して入力テキストをレンダリングします。
`It` はフォームヘルパーを指していると思うので、少々くどいですが明記して
「すると、フォームヘルパーはこのフィールドコンストラクタを使って入力テキストをレンダリングします。」
としてはどうでしょう？

2017-07-27 11:36 UTC, 12345 commented
ご確認ありがとうございます。
ご指摘いただいた内容で修正してみましたのでご確認よろしくお願いいたします。

> この部分、2.2.x からスカっと抜けてますね...こちらでバックポートしておきます。

確かに、目次ごと存在しないですね・・・
よろしくお願いします！

2017-07-27 21:44 UTC, garbagetown approved these changes

2017-07-27 21:45 UTC, garbagetown commented
ご対応ありがとうございます！

2017-07-27 21:45 UTC, merged