translate #1295
playframework-ja/translation-project pull request #1432
Opened 2017-08-03 14:21 UTC by 12345

新規翻訳です。

2017-08-04 22:34 UTC, garbagetown requested changes
ありがとうございます！

数点コメントしましたので、適宜ご対応ください。対応不要と思うものがあれば、その旨コメントいただければ結構です :smiley:

2017-08-04 22:34 UTC, garbagetown commented on manual/working/scalaGuide/main/json/ScalaJsonHttp.md
> +エンティティのリストを GET したり、新しいエンティティを作成する POST を受け入れる、簡単な RESTful Web サービスを設計することにより、必要な概念を説明します。このサービスでは、すべてのデータに JSON のコンテンツタイプが使用されます。
`The service will use a content type of JSON` は受動態ではないので「JSON のコンテンツタイプを使用します。」でよいと思います。

2017-08-04 22:34 UTC, garbagetown commented on manual/working/scalaGuide/main/json/ScalaJsonHttp.md
> +`Action` は `Place` オブジェクトのリストを取得し、暗黙の `Writes[Place]` 付きの `Json.toJson` を使って `JsValue` に変換し、これを結果のボディとして返します。Play は結果を JSON として認識し、適切な `Content-Type` ヘッダとレスポンス用のボディ値を設定します。
"with our implicit `Writes[Place]`" は、ひとつ前の段落で定義した暗黙の `Writes[Place]` を使って変換することを意味しているので、直訳すると「暗黙の `Writes[Place]` と共に `Json.toJson` を使って」となり、多少意訳すると「暗黙の `Writes[Place]` による `Json.toJson` を使って」などになるのかな、と思いました。

2017-08-04 22:34 UTC, garbagetown commented on manual/working/scalaGuide/main/json/ScalaJsonHttp.md
> +- リクエストを解析したり、`request.body` を `JsValue` として提供する、JSON 固有の `BodyParser` を使用します。
"JSON specific `BodyParser`" は「JSON に特化した `BodyParser`」でいかがでしょう？

2017-08-04 22:34 UTC, garbagetown commented on manual/working/scalaGuide/main/json/ScalaJsonHttp.md
> +- この `Action` は、`Content-Type` ヘッダが `text-json` や `application/json` となっているリクエストと、作成するエンティティの JSON 表現を含むボディを要求します。
"expects" なので「期待します。」くらいで良いかと :relieved:

2017-08-04 22:34 UTC, garbagetown commented on manual/working/scalaGuide/main/json/ScalaJsonHttp.md
> +Play は JSON を用いた REST をサポートするように設計されており、これらのサービスの開発作業はやり易くなるでしょう。作業の大部分は、モデルの `Reads` と `Writes` を記述することになります。詳細については次の章で説明します。
"should hopefully be straightforward" は、言いたいことは分かるけど訳しづらいですねｗ
直訳すると「おそらくまっすぐ進むことになるでしょう」で、多少やわらかく意訳して「すんなりと進むことでしょう」などでもよいかな？と思いました。

2017-08-04 22:34 UTC, garbagetown commented on manual/working/scalaGuide/main/json/ScalaJsonHttp.md
> +- バリデーションの結果を処理するために、エラーと成功のフローを持つ `fold` を使用しました。このパターンは、[[フォームの送信|ScalaForms]] でも使用されているのでよく知られているかもしれません。
「使用されているのでよく知られている」は読点を入れて「使用されているので、よく知られている」とすると、より読み易くなるかなーと思います。

2017-08-05 13:17 UTC, 12345 commented
ご確認ありがとうございます！
ご指摘いただいた内容で修正しましたのでご確認をお願いします！

> "should hopefully be straightforward" は、言いたいことは分かるけど訳しづらいですねｗ

こういうのがたまに出てきますよねー
訳のご提案ありがとうございます！:smile:

2017-08-08 07:20 UTC, garbagetown commented
ご対応ありがとうございます。確認しました :relieved:

2017-08-08 07:20 UTC, merged