translate #1294
playframework-ja/translation-project pull request #1433
Opened 2017-08-04 15:31 UTC by 12345

新規翻訳です。

2017-08-04 22:36 UTC, garbagetown commented on manual/working/scalaGuide/main/json/ScalaJsonCombinators.md
> +[[JSON の基本|ScalaJson]] では、[`JsValue`](api/scala/play/api/libs/json/JsValue.html) 構造体と他のデータ型との変換に使用されるコンバータ [`Reads`](api/scala/play/api/libs/json/Reads.html) と [`Writes`](api/scala/play/api/libs/json
:+1:

2017-08-05 03:14 UTC, garbagetown requested changes
ありがとうございます！
数点コメントしましたので、ご確認のうえ適宜ご対応下さい :-)

2017-08-05 03:14 UTC, garbagetown commented on manual/working/scalaGuide/main/json/ScalaJsonCombinators.md
> +[`JsPath`](api/scala/play/api/libs/json/JsPath.html) は、`Reads`/`Writes` を作るための中核となる構成要素です。`JsPath` は `JsValue` 構造体におけるデータの位置を表します。`JsValue` を走査するのと同様の構文を使って、`JsPath` オブジェクト (ルートパス) を使用して `JsPath` の子イ
「走査するのと」が、ちょっと口語的に感じました。
また、"by using" なので「使うことにより」とすると全体が読みやすくなるかと。
最後に「〜することができます」は、少々くどいので「〜できます」で良いと思いました。

総合して「`JsValue` を走査する構文と同様のものを使うことにより、(ルートパスの) `JsPath` オブジェクトを使って `JsPath` 子インスタンスを定義できます。」などとなるでしょうか。

2017-08-05 03:14 UTC, garbagetown commented on manual/working/scalaGuide/main/json/ScalaJsonCombinators.md
> +[`play.api.libs.json`](api/scala/play/api/libs/json/package.html) パッケージは、`JsPath` の別名として `__` (ダブルアンダースコア) を定義します。必要に応じてこれを使用することができます。
ここも「使用できます」で良いですね :relieved:

2017-08-05 03:14 UTC, garbagetown commented on manual/working/scalaGuide/main/json/ScalaJsonCombinators.md
> +理解をより簡単にするために、組み合わせた機能を 2 つのステートメントに分解します。最初に、`and` コンビネータを使用して `Reads` オブジェクトを結合します。
"For easier understanding" は、サクッと「分かりやすくするために」でも良いかもですねｗ

2017-08-05 03:14 UTC, garbagetown commented on manual/working/scalaGuide/main/json/ScalaJsonCombinators.md
> +個々の値をモデルに変換する関数を持つ `CanBuildX` の 2 番目の `apply` メソッドを呼び出すと、複雑な `Reads` が返されます。コンストラクタのシグネチャが一致するケースクラスがある場合は、単にその `apply` メソッドを使うことができます。
"Second" は、分解したステートメントの二つ目のことを指しており、ひとつめの "First" を「最初に」と訳しているので、「次に」などとしたほうが分かり易いかなと思いました。

「次に、個々の値をモデルに変換する関数を持つ `CanBuildX` の `apply` メソッドを呼び出すと、複雑な `Reads` が返ります」としてはどうでしょう？

2017-08-05 03:14 UTC, garbagetown commented on manual/working/scalaGuide/main/json/ScalaJsonCombinators.md
> +- `Reads[A] or Reads[B] => Reads` - 論理 OR を実行し、最後の `Reads` の結果をチェックし続ける演算子。
この "keep" は「保つ、保持する」という意味で、「論理 OR を実行し、最後の `Reads` の結果を保持する演算子。」かなと思いました。

2017-08-05 03:14 UTC, garbagetown commented on manual/working/scalaGuide/main/json/ScalaJsonCombinators.md
> +`JsPath` と、`Reads` に非常によく似たコンビネータを使って複雑な `Writes` を構築することができます。
「非常に」の語感が強く感じました。「とてもよく似た」くらいでいかがでしょう？

また "Here's the `Writes` for our example model:" の訳が抜けているようです :-)

2017-08-05 03:14 UTC, garbagetown commented on manual/working/scalaGuide/main/json/ScalaJsonCombinators.md
> +例題モデルが示していない特殊なケースの 1 つは、再帰型に対して `Reads` と `Writes` をどのように扱うかです。`JsPath` は、これを処理するための名前による引数を取る `lazyRead` メソッドと `lazyWrite` メソッドを提供します。
"how to ~" を「〜する方法」と訳して、「例題モデルが示していない特殊なケースの 1 つは、再帰型に対して `Reads` と `Writes` を扱う方法です。」としてはいかがでしょう？

2017-08-05 13:59 UTC, 12345 commented
ご確認ありがとうございます。

ご指摘いただいた内容での修正、翻訳し忘れの箇所の翻訳、およびそこで出てきた `example model` の訳の他所での表記ゆれの修正を行いました。

2017-08-08 07:17 UTC, garbagetown commented
ご対応ありがとうございます！確認しました :smiley:

2017-08-08 07:17 UTC, merged