translate #1279
playframework-ja/translation-project pull request #1434
Opened 2017-08-14 13:31 UTC by 12345

2.3.xの流用＋新規翻訳＋αです。

2017-08-15 13:42 UTC, garbagetown requested changes
ありがとうございます！確認して数点コメントしました。
ご確認のうえ、適宜ご対応ください :-)

2017-08-15 13:42 UTC, garbagetown commented on manual/working/scalaGuide/main/cache/ScalaCache.md
> +データのキャッシュは、近年のアプリケーションでは典型的な最適化であるため、Play はグローバルキャッシュを提供します。
この "global" は「全体的な、包括的な」のような意味だと思います。

2017-08-15 13:42 UTC, garbagetown commented on manual/working/scalaGuide/main/cache/ScalaCache.md
> +> キャッシュに関する重要な点は、格納したデータが消失するかのようにふるまうことです。
こういう本質的にあまり意味のないちょっとカッコいい原文やめてほしいですね^^;
むずかしいところを上手に訳していただいてありがとうございます 😃

2017-08-15 13:42 UTC, garbagetown commented on manual/working/scalaGuide/main/cache/ScalaCache.md
> +キャッシュに格納されたデータのために、データが失われた場合に備えて再生手段を用意しておく必要があります。この哲学は Play を支える基本のひとつであり、セッションがその有効期間の間ずっと値を保持することが期待されている Java EE とは異なります。
この ”For" は「～に関して、～について」のような意味だと思います。
また、細かいですが 「有効期間の間」は「間」が続いてちょっと読みづらいかも？と思いました。「その生存期間を通じて」などではいかがでしょう？

2017-08-15 13:42 UTC, garbagetown commented on manual/working/scalaGuide/main/cache/ScalaCache.md
> +異なるキャッシュにアクセスすることは可能です。デフォルトのキャッシュは `play` と呼ばれ、`ehcache.xml` というファイルを作成することにより設定できます。追加のキャッシュは、別の構成設定によって設定や実装ができます。
「アクセスすることは可能です」が、「～は不可能だけど、アクセスすることは可能」のように読めるかも？と思いました。シンプルに「別のキャッシュにアクセスすることができます」などはいかがでしょう？

また、"or even implementations" は "be configured with" に掛かっていると思うので、「追加のキャッシュは別の設定、または実装によっても構成できます」などになるのかなーと思いました :-)

2017-08-15 13:42 UTC, garbagetown commented on manual/working/scalaGuide/main/cache/ScalaCache.md
> +複数の異なる Ehcache キャッシュにアクセスしたい場合、そのバインドを `application.conf` で Play に知らせる必要があります。このような感じです。
"tell Play to bind them in" なので、直訳すると「それらを application.conf 中に結びつけて Play に知らせる」となり、多少違約すると「それらを application.conf 内に記述して Play に区別させる」などでしょうか。

2017-08-15 13:42 UTC, garbagetown commented on manual/working/scalaGuide/main/cache/ScalaCache.md
> +[Cached](api/scala/play/api/cache/Cached.html) クラスはキャッシュのアクションを作成するのに役立ちます。
「キャッシュのアクション」がちょっと分かりづらいかも？と思いました。意味としては結果をキャッシュできるアクションのことなので、「キャッシュされるアクション」などとなるのかなーと思います :-)

2017-08-15 13:42 UTC, garbagetown commented on manual/working/scalaGuide/main/cache/ScalaCache.md
> +結果が変化する時、異なるキーを使ってそれぞれの結果をキャッシュすることができます。この例では、それぞれのユーザーは異なるキャッシュ結果を持ちます。
この "If" は「場合」くらいでよさそうですね。
"each user has a different cached result" は直訳すると固い感じになるので、思い切って「それぞれの結果はユーザごとにキャッシュされます」くらいまで意訳しちゃってもいいかもです :-)

2017-08-15 13:42 UTC, garbagetown commented on manual/working/scalaGuide/main/cache/ScalaCache.md
> +[CacheApi](api/scala/play/api/cache/CacheApi.html) のカスタム実装を提供することは可能ですが、置き換えるか、デフォルト実装と並行して使用するかのどちらかになります。
"sit along side" は「隣に座って」が転じて「寄り添って、一緒に」みたいな意味だと思います。「平行して」だとparallelのように誤解する人もいるのかな？と思いました。
"that either ~ or" は "implementation of the CacheApi" に掛かるので、直訳すると「デフォルト実装を置き換える、または隣に座る CacheApi の独自実装を提供できます」となり、意味が通じるように意訳すると「デフォルト実装を置き換えるか、または合わせて使う CacheApi の独自実装を提供できます」みたいな感じかなーと思いました :-)

2017-08-15 13:42 UTC, garbagetown commented on manual/working/scalaGuide/main/cache/ScalaCache.md
> +キャッシュ API の実装を提供するには、デフォルトの実装に加え、カスタムの修飾子を作るか、`NamedCache` 修飾子を再利用するかして実装をバインドします。
"in addtion to~" は "To provide an implementation~" に掛かると思うので、「デフォルトの実装に加えて cache API の実装を提供するには」だと思います。

2017-08-16 14:09 UTC, 12345 commented on manual/working/scalaGuide/main/cache/ScalaCache.md
> +> キャッシュに関する重要な点は、格納したデータが消失するかのようにふるまうことです。
ほんと、困っちゃいますよねぇ・・・:weary:

2017-08-16 14:11 UTC, 12345 commented
ご確認ありがとうございます！:smile:
ご指摘いただいた内容で修正いたしました。
再度ご確認をお願いします！

2017-08-17 03:12 UTC, garbagetown commented
ご対応ありがとうございます！確認しました :smiley:

2017-08-17 03:12 UTC, merged