translate #1274
playframework-ja/translation-project pull request #1435
Opened 2017-08-23 11:08 UTC by 12345

2.3.x流用＋新規翻訳＋αです。

2017-08-23 15:45 UTC, garbagetown commented
ありがとうございます！今週末 08/26 目処で確認させていただきます :bowing_man:

2017-08-24 01:27 UTC, 12345 commented
よろしくお願いします！:smile:

2017-08-26 20:50 UTC, garbagetown requested changes
ご対応ありがとうございます！数点コメントさせていただきましたので、ご確認の上、適宜ご対応下さい。

内容が難しかったので、指摘誤りもあるかもしれません。その際はご遠慮なくコメントください :bowing_man:

2017-08-26 20:50 UTC, garbagetown commented on manual/working/scalaGuide/main/akka/ScalaAkka.md
> +* 送受信を行うメッセージやその _手順_ は、コンパニオンオブジェクトに定義されています。
「送受信を行うメッセージ」だと、メッセージが主語のように読めてしまうかも？と思いました。
"The messages it sends/receives, or its protocol" の "it" はアクターだと思うので、「アクターが送受信するメッセージや手順」でしょうか。

2017-08-26 20:50 UTC, garbagetown commented on manual/working/scalaGuide/main/akka/ScalaAkka.md
> +* 同様に `props` メソッドもコンパニオンオブジェクトに定義されていて、アクターを作成するための props を返します。
文法的には "that returns the props" は "its companion object" に掛かっていると思うのですが、意味的には "props method" に掛かっているようにも読めました。

ので、読みやすく順序を入れ替えて「同様に、アクターを作成するためのプロパティを返す props メソッドをコンパニオンオブジェクトに定義しています」としても良いかなと思いました。

2017-08-26 20:50 UTC, garbagetown commented on manual/working/scalaGuide/main/akka/ScalaAkka.md
> +アクターの作成や使用には、`ActorSystem` が必要です。ActorSystem で依存関係を宣言することにより取得します。
"dependency on an ActorSystem" なので「ActorSystem への依存関係」ですね。コード例も

```scala
@Inject() (system: ActorSystem)
```

と、ActorSystem をインジェクションしています。

"can be" や "like so" も含めて多少意訳すると「この ActorSystem は次のように依存関係を宣言することで取得できます。」などとなるでしょうか。

2017-08-26 20:50 UTC, garbagetown commented on manual/working/scalaGuide/main/akka/ScalaAkka.md
> +`actorOf` メソッドは新規のアクターを作成するために使われます。このコントローラーはシングルトンとして宣言することに注意して下さい。これはアクターの作成や参照の保存のために必要で、仮に、このコントローラーがシングルトンの適用範囲外の場合、新しいアクターはコントローラーが作成される都度作成されることになり、同一システム内で同一名称のアクターを 2 つは持てないため、最終的に例外をスローする
長い文をきれいに訳していただいてありがとうございます！

原文が長くて強引に訳すと読みにくくなってしまうと思われる場合は、適当に文を分けて頂いても大丈夫です :relieved:

2017-08-26 20:50 UTC, garbagetown commented on manual/working/scalaGuide/main/akka/ScalaAkka.md
> +アクターを使ってできる最も基本的なことは、アクターにメッセージを送信することです。メッセージをアクターに送信しても応答は得られず、送信しっ放しとなります。これは _tell_ パターンとしても知られています。
"it's fire and forget." の部分、「アクターは送信するだけして、あとは忘れます」的な意味ということは分かりますが、文法をどう解釈すればいいんですかね...?
"it's fire" は "it is fire" としか読めず、となると "fire" は名詞になるし、"and forget" が "it's" に掛かるとすると "it is forget" だけど、"forget" は動詞なので現在形だと文法的に成立しないような...

2017-08-26 20:50 UTC, garbagetown commented on manual/working/scalaGuide/main/akka/ScalaAkka.md
> +* 暗黙のタイムアウトは適用範囲内において必要で、ask パターンはタイムアウトを持つべきです。アクターが応答よりも長くかかった場合、返された future はタイムアウトエラーで完了します。
"If the actor takes longer than that to respond" の "that" はタイムアウトを指していると思います。また、"to respond" は "takes" に掛かっていると読めるので、「アクターが応答にタイムアウトよりも長い時間を掛けた場合は」などとなるでしょうか。

2017-08-26 20:50 UTC, garbagetown commented on manual/working/scalaGuide/main/akka/ScalaAkka.md
> +Play は、アクターのバインドに役立つ、いくつかのヘルパーを提供します。それらはアクター自身が依存性注入されることを許可し、アクターのためのアクターの参照が他のコンポーネントに注入されることも許可します。これらのヘルパーを用いたアクターをバインドするには、[[依存性注入ドキュメント|ScalaDependencyInjection#Play-applications]] の説明に従ってモジュー
この辺りの文章、自分にはかなり難しく感じられましたが、上手に訳して頂いてありがとうございます！

"and allows the actor ref for the actor to be injected" の部分ですが、"the actor ref for the actor" は「アクターのためのアクターの参照」ではなく、「そのアクターに対するアクター参照」かなと思いました。actor ref は [ActorRef](http://doc.akka.io/japi/akka/current/akka/actor/ActorRef.html) のことだと思います。

要は「ヘルパーを使うことで、アクターそのものをインジェクションすることもできるし、そのアクターに対するアクター参照をインジェクションすることもできるようになる」と言いたいのだと思います。

2017-08-26 20:50 UTC, garbagetown commented on manual/working/scalaGuide/main/akka/ScalaAkka.md
> +このアクターは `configured-actor` という名前になり、また `configured-actor` という名前での注入が適切です。コントローラーや他のコンポーネントのアクターに依存することができます。
ここも分かりづらいですね...

Guice を使ったインジェクションの話で、急に Java っぽい内容になっているように読めるので、"qualified" は限定子(qualifire) のことを指しているのだと思います。

要するに、アクターは "configured-actor" という名前の Bean で Guice コンテナに登録されて、同じく "configured-actor" という限定子を "＠Named" に指定することで当該 Bean をインジェクションできる、と言いたいのだと思います。

もし Guice によるインジェクションや Qualifire をご存知ないようでしたら、以下が参考になるかと思います。
- [JavaEE7をはじめよう(13) - インジェクション候補が複数ある場合の対処方法 - エンタープライズギークス (Enterprise Geeks)](http://enterprisegeeks.hatenablog.com/entry/2015/07/13/080329)

2017-08-26 20:50 UTC, garbagetown commented on manual/working/scalaGuide/main/akka/ScalaAkka.md
> +また、`key` を持ち `Actor` を返す `Factory` トレイトを定義しました。これを実装しない場合、Guice は `key` パラメータを渡すだけでなく、`Configuration` 依存関係を配置し注入する実装も提供します。このアクターのテストを行った時、トレイトは単に `Actor` を返すので、任意のアクターを返すファクトリーを注入することができます。例えば、実際の子ア
Guice の AssistedInjection についてよく知らないので、この辺を調べながらレビューしています :bowing_man: 

[心地良すぎるDependency Injectionライブラリ Guice - nodchipの日記](http://d.hatena.ne.jp/nodchip/20130126/1359161946)

"We won't implement this, Guice will do that for us, providing an implementation" は、宣言した Factory トレイトは Guicde が自動生成するので自分たちで実装することはない、と言っていますね。

この自動生成を実行する際に "that not only passes our `key` parameter, but also locates the `Configuration` dependency and injects that. " ということで、引数の key を渡すだけではなく、Configuration への依存性も注入する、ということのようです。

で、このトレイトは Actor を返すだけなので、このアクターをテストをする際には、任意のアクターを返すファクトリをインジェクションできますよ、と。

なかなかむずかしい... :sweat:

2017-08-26 20:50 UTC, garbagetown commented on manual/working/scalaGuide/main/akka/ScalaAkka.md
> +`ConfiguredChildActor.Factory` のインスタンスを自動的にバインドするために Guice を取得し、インスタンス化の際に `Configuration` のインスタンスを `ConfiguredChildActor` に提供します。
"get Guice to automatically bind" は「Guice に自動的にバインドさせる」のような意味だと思います。

"when it's instantiated" の "it" は "ConfiguredChildActor.Factory" だと思います。

直訳すると「これで Guice に、インスタンス化の際に  ConfiguredChildActor に Configuration のインスタンスを提供する ConfiguredChildActor.Factory のインスタンスを自動的にバインドさせます。」となりますが、ものすごく読みづらいので、文を分けて
「これで Guice に ConfiguredChildActor.Factory のインスタンスを自動的にバインドさせます。ConfiguredChildActor.Factory は、インスタンス化の際に  ConfiguredChildActor に Configuration のインスタンスを提供します。」あたりで良いかと思いました。

ここもむずかしいですね :sweat:

2017-08-26 20:50 UTC, garbagetown commented on manual/working/scalaGuide/main/akka/ScalaAkka.md
> +`akka` 接頭辞の代わりに `my-akka` 接頭辞から設定が読み込まれます。
"Now" のニュアンスを「これで」「これにより」などで表現されてはどうでしょう？

2017-08-26 20:50 UTC, garbagetown commented on manual/working/scalaGuide/main/akka/ScalaAkka.md
> +組み込みのアクターシステムの使用をおすすめしますが、正しいクラスローダー、ライフサイクルのフックなどをすべてセットアップするような独自のアクターシステムを使用することは全然構いません。ただし、次のことを確実に行うことが重要です。
"as it sets up ~" はビルトインのアクターシステムをおすすめする理由ですね。「クラスローダー、ライフサイクルのフックなどをすべて正しくセットアップするので、組み込みのアクターシステムの使用をおすすめします」かと。

2017-08-26 20:50 UTC, garbagetown commented on manual/working/scalaGuide/main/akka/ScalaAkka.md
> +* Play が停止した時にアクターシステムを停止させるための [[停止フック|ScalaDependencyInjection#Stopping/cleaning-up]] の登録。
箇条書きなので体言止めすると見栄えが良いですが、三つ目の箇条書きで体言止めが崩れていますし、"Register" や "Pass" は名詞ではないので、そのまま「〜を登録する」「〜を渡す」などと訳してよいと思います :relieved:

2017-08-28 14:52 UTC, 12345 commented on manual/working/scalaGuide/main/akka/ScalaAkka.md
> +アクターを使ってできる最も基本的なことは、アクターにメッセージを送信することです。メッセージをアクターに送信しても応答は得られず、送信しっ放しとなります。これは _tell_ パターンとしても知られています。
`fire-and-forget` で名詞として使われることがあるらしいです。

2017-08-28 14:55 UTC, 12345 commented
今回も多岐に渡る丁寧なご指摘ありがとうございます！
修正を行いましたので再度ご確認をお願いします。

2017-08-28 15:34 UTC, garbagetown commented on manual/working/scalaGuide/main/akka/ScalaAkka.md
> +アクターを使ってできる最も基本的なことは、アクターにメッセージを送信することです。メッセージをアクターに送信しても応答は得られず、送信しっ放しとなります。これは _tell_ パターンとしても知られています。
おー！知りませんでした。ありがとうございます！！
- [fire and forgetの意味・用例｜英辞郎 on the WEB：アルク](http://eow.alc.co.jp/search?q=fire%20and%20forget)

2017-08-28 15:58 UTC, garbagetown commented
ご対応ありがとうございます！確認しました！

2017-08-28 15:58 UTC, merged