translate #1301
playframework-ja/translation-project pull request #1438
Opened 2017-09-15 10:37 UTC by 12345

すべて新規翻訳です。

2017-09-16 06:25 UTC, garbagetown commented
これはまた大作をありがとうございます。09/18までに確認させてください！

2017-09-16 06:37 UTC, 12345 commented
了解です！:smile:
なんか大作にブチ当たってしまいました・・・:cry:
いつでもよいのでよろしくお願いしますm(_ _)m

2017-09-18 15:21 UTC, garbagetown commented
確認して数点コメント致しました。ご確認の上、必要に応じて適宜ご対応頂ければと思います :bowing_man:

2017-09-18 15:22 UTC, garbagetown requested changes
確認して数点コメント致しました。ご確認の上、必要に応じて適宜ご対応頂ければと思います :bowing_man:

2017-09-18 15:22 UTC, garbagetown commented on manual/working/scalaGuide/main/tests/ScalaFunctionalTestingWithScalaTest.md
> +Playには、機能テストを支援する、多くのクラスや便利なメソッドが用意されています。これらの大半は、[`play.api.test`](api/scala/play/api/test/package.html) パッケージか [`Helpers`](api/scala/play/api/test/Helpers$.html) オブジェクトに含まれています。[_ScalaTest + Play_]
"integration library builds on this testing support for ScalaTest" は "integration library / builds on / this testing support for ScalaTest" で分かれるのかなと思います。
直訳すると「統合ライブラリは、このScalaTestのテスト支援に基づいています」でしょうか。

2017-09-18 15:22 UTC, garbagetown commented on manual/working/scalaGuide/main/tests/ScalaFunctionalTestingWithScalaTest.md
> +すべての Play 組み込みのテスト支援と _ScalaTest + Play_ は、次のようなインポートによって利用できます。
"like" などで修飾されていないので、「ような」は省いて「次のインポートによって」と断言してしまって良いと思います。

2017-09-18 15:22 UTC, garbagetown commented on manual/working/scalaGuide/main/tests/ScalaFunctionalTestingWithScalaTest.md
> +Play では頻繁に [`Application`](api/scala/play/api/Application.html) をコンテキストとして実行する必要がありますが、これはたいてい [`play.api.Play.current`](api/scala/play/api/Play$.html) によって提供されます。
"a running Application" で「実行中のアプリケーション」でしょうか。

2017-09-18 15:22 UTC, garbagetown commented on manual/working/scalaGuide/main/tests/ScalaFunctionalTestingWithScalaTest.md
> +_ScalaTest + Play_ が `OneAppPerSuite` と `OneAppPerTest` の両方を提供する理由は、テストの実行を最も速くさせる方法を選択できるようにするためです。もし、連続したテストの中でアプリケーションの状態を維持したい場合は `OneAppPerSuite` を使う必要があります。しかし、各テストでクリーンな状態を望む場合は `OneAppPerTest
"If each test needs a clean slate, however, you could either use `OneAppPerTest` or use `OneAppPerSuite`, but clear any state at the end of each test."
の "however" は「しかし」という否定的な意味合いよりも「一方で」のような意味かと。また、"but clear any state~" は OneAppPerSuite だけでなく、OneAppPerTest でも同様だと思います。

「一方で、各テストでクリーンな状態が必要な場合は、`OneAppPerTest` または `OneAppPerSuite` のいずれかを使えますが、各テストの最後であらゆる状態をクリアしてください。」などでいかがでしょうか。

2017-09-18 15:22 UTC, garbagetown commented on manual/working/scalaGuide/main/tests/ScalaFunctionalTestingWithScalaTest.md
> +`OneServerPerSuite` および `OneServerPerTest` トレイトは、サーバーが実行しているポート番号を `port` フィールドとして提供します。デフォルトは 19001 ですが、`port` を上書きするか、システムプロパティ `testserver.port` を設定することにより変更できます。これは、各ビルドごとにポートを動的に予約できるので、継続的な統合サー
"This can be useful for integrating with continuous integration servers, so that ports can be dynamically reserved for each build." は、なんだかスムーズに読めないですね...
全体の意図はなんとなく分かるのですが、"This" は前の節を表しているのか？ "so that ~" はどこに掛かっているのか？が、すっきり理解できません。
いまいち自信ありませんが、"This can be useful ~, so that ~" は「こうすると便利なので〜」なのかな、と思いました。

「継続的統合サーバーに組み入れる際に便利なので、各ビルドごとにポートを動的に予約できます」とか...?

2017-09-18 15:22 UTC, garbagetown commented on manual/working/scalaGuide/main/tests/ScalaFunctionalTestingWithScalaTest.md
> +テストクラスのすべてのテストを同一ブラウザインスタンスを使用して実行するには、テストクラスに [`OneBrowserPerSuite`](http://doc.scalatest.org/plus-play/1.0.0/index.html#org.scalatestplus.play.OneBrowserPerSuite) をミックスインします。また、[`ChromeFactory`](ht
:+1:

2017-09-18 15:22 UTC, garbagetown commented on manual/working/scalaGuide/main/tests/ScalaFunctionalTestingWithScalaTest.md
> +例として、`OneServerPerSuite` と `HtmUnitFactory` をミックスインした次のようなテストクラスがあります。
ここは文型を変えて意訳しなくても素直に読めるかなと思いました。
「例えば、以下のテストクラスは`OneServerPerSuite` と `HtmUnitFactory` をミックスインします」で十分かと。

2017-09-18 15:22 UTC, garbagetown commented on manual/working/scalaGuide/main/tests/ScalaFunctionalTestingWithScalaTest.md
> +もし、複数の Web ブラウザでテストを行いたい場合は、対応させたいすべてのブラウザでアプリケーションが正しく動作するように、[`AllBrowsersPerSuite`](http://doc.scalatest.org/plus-play/1.0.0/index.html#org.scalatestplus.play.AllBrowsersPerSuite) または [`AllBrowser
"to ensure your application works correctly in all the browsers you support, " は前の節に掛かっていると思います。
「アプリケーションがサポートするすべてのブラウザで正しく動作することを保証するために、テストを複数の web ブラウザで実行したい場合は、」ではないでしょうか。

2017-09-18 15:22 UTC, garbagetown commented on manual/working/scalaGuide/main/tests/ScalaFunctionalTestingWithScalaTest.md
> +`sharedTests` によって宣言されたすべてのテストは、`browsers` フィールドで定義されている、ホストシステムで利用可能なすべてのブラウザで実行されます。ホストシステムで利用できない、いずれのブラウザのテストも自動的にキャンセルされます。スイートの各テストが (ScalaTest によって要求された) 一意的な名前を持つように、テスト名に `browser.name` を手動で
"so long as ~" は "as long as ~" と同じで、「〜である限りは」なので、「それらがホストシステムで利用できれば」などになるかと思います。

2017-09-18 15:22 UTC, garbagetown commented on manual/working/scalaGuide/main/tests/ScalaFunctionalTestingWithScalaTest.md
> +前述のテストクラスは、Firefox と Chrome で共有されたテストの実行を試みるだけです (そしてブラウザが利用できない場合は自動的にテストはキャンセルされます)。
"only" は文法的に "attempt to run" に掛かっているように見えますが、文脈的に "with Firefox and Chrome" に掛かっているようにも思えます。「Firefox と Chrome でのみ、共有された〜」ではないでしょうか。

2017-09-18 15:22 UTC, garbagetown commented on manual/working/scalaGuide/main/tests/ScalaFunctionalTestingWithScalaTest.md
> +`MixedFixtures` は ScalaTest の [`fixture.Suite`](http://doc.scalatest.org/2.1.5/index.html#org.scalatest.fixture.Suite) を必要とし、`PlaySpec` は まさに標準の [`Suite`](http://doc.scalatest.org/2.1.5/index.html#or
"just" は「単なる」という意味だと思います。「単なる標準の Suite であるため」でしょうか。

2017-09-18 15:22 UTC, garbagetown commented on manual/working/scalaGuide/main/tests/ScalaFunctionalTestingWithScalaTest.md
> +Web サービスの呼び出しを行う時、[`WSTestClient`](api/scala/play/api/test/WsTestClient.html) を使用することができます。`wsCall` と `wsUrl` の 2 つの呼び出しが可能で、それぞれ Call および文字列を引数に取ります。`WithApplication` のコンテキスト内での呼び出しが期待されていることに注意してくだ
"Call or a string" なので「Call または文字列」でしょうか。

2017-09-22 10:28 UTC, 12345 commented
ご確認ありがとうございます！:smile:
修正しましたので再度ご確認をお願いします！m(_ _)m

2017-09-25 22:04 UTC, merged

2017-09-25 22:04 UTC, garbagetown commented
ご対応ありがとうございます！確認しました :relieved: