translate #1302
playframework-ja/translation-project pull request #1439
Opened 2017-09-29 10:40 UTC by 12345

ScalaFunctionalTestingWithScalaTestからの流用＋新規翻訳です。

2017-10-03 22:25 UTC, garbagetown commented
すみません、10/07〜10/09の三連休で確認させてください！

2017-10-04 11:22 UTC, 12345 commented
了解です！よろしくお願いします！:bow:

2017-10-10 21:05 UTC, garbagetown requested changes
遅くなり申し訳ありません。確認して一点コメントいたしましたので、ご確認ください 。

2017-10-10 21:05 UTC, garbagetown commented on manual/working/scalaGuide/main/tests/ScalaFunctionalTestingWithSpecs2.md
> +もし、ブラウザを使用したアプリケーションのテストを行いたい場合は、[Selenium WebDriver](https://github.com/seleniumhq/selenium) を使用できます。Play は WebDriver を開始し、[`WithBrowser`](api/scala/play/api/test/WithBrowser.html) を用いた [FluentLeniu
`wrap it in the convenient API provided by [FluentLenium](https://github.com/FluentLenium/FluentLenium) using [`WithBrowser`]` は using が wrap it に掛かっていると思うので、"WithBrowser を使って FluentLenium が提供する便利な API でラップします" でしょうか。

また、`you can change the port, [`Application`](api/scala/play/api/Application.html), and you can ~` の `Application` が抜けているようです。

2017-10-11 12:13 UTC, 12345 commented
ご確認ありがとうございます！
修正いたしましたので、再度ご確認をお願いします。:bow:

2017-10-12 20:43 UTC, merged

2017-10-12 20:44 UTC, garbagetown commented
ありがとうございます。マージしました :tada: