translate #1267
playframework-ja/translation-project pull request #1445
Opened 2018-01-22 10:34 UTC by 12345

2.3の流用＋未訳分の翻訳＋修正です。

2018-01-22 10:45 UTC, 12345 commented on manual/working/scalaGuide/advanced/http/ScalaHttpFilters.md
> +対照的に、[[アクション組成|ScalaActionsComposition]] は認証や認可、キャッシュなど、特定のルートに対する関心事を対象としています。もし、フィルターをすべてのルートに適用したいのでなければ、代わりにアクション組成の使用を検討してみてください。アクション組成はフィルターよりも遙かに強力です。また、定型的なコードを最小限にするために、ルート毎に独自の定義済みアクション群を構
以前、`ScalaActionsComposition`のページを訳した時に、`action composition`を`アクション構成`と訳したのですが、今回のページにも何回か`action composition`が出て来たので改めて考えてみたのですが、`合成`でも`構成`でもしっくり来なかったので、`組成`と訳してみました。（「組み立てられたアクション」とか「アクションを組み立てたもの」みたいな意味合いなのかなと考えました）

2018-02-03 02:47 UTC, garbagetown requested changes
大変遅くなり申し訳ございません。数点コメントさせて頂きましたので、適宜取捨選択して頂けますでしょうか。

2018-02-03 02:47 UTC, garbagetown commented on manual/working/scalaGuide/advanced/http/ScalaHttpFilters.md
> +ここで何が起こっているのかを見てみましょう。最初に注文すべきは `apply` メソッドのシグネチャです。これはカリー化された関数で、最初のパラメータ `nextFilter` はリクエストヘッダを取得して結果を生成する関数で、次のパラメータ `requestHeader` は受信するリクエストの実際のリクエストヘッダです。
`最初に注文すべきは` は `最初に注目すべきは` でしょうか？

2018-02-03 02:47 UTC, garbagetown commented on manual/working/scalaGuide/advanced/http/ScalaHttpFilters.md
> +ここで何が起こっているのかを見てみましょう。最初に注文すべきは `apply` メソッドのシグネチャです。これはカリー化された関数で、最初のパラメータ `nextFilter` はリクエストヘッダを取得して結果を生成する関数で、次のパラメータ `requestHeader` は受信するリクエストの実際のリクエストヘッダです。
`カリー化された関数で、(snip)生成する関数で、` と `関数で` がくり返されており少し気になりました。
`カリー化された関数で、(snip)生成する関数であり` など言い回しを変えてみるか、思い切って `カリー化された関数です。(snip)生成する関数で、` と文を分けてしまっても良いのかなと思いましたが、いかがでしょう。

2018-02-03 02:47 UTC, garbagetown commented on manual/working/scalaGuide/advanced/http/ScalaHttpFilters.md
> +`nextFilter` パラメータはフィルタチェーン内の次のアクションを表します。これを呼び出すとアクションが呼び出されます。ほとんどの場合、将来的にはいつでもこのメソッドを呼び出すことになります。なんらかの理由でリクエストをブロックしたい場合は、これを呼び出さないようにします。
`Invoking it` の `it` はフィルタチェーンでしょうか。
直訳すると `フィルタチェーンを呼び出すことが次のアクションが呼び出されることを引き起こします` となり、意訳すると `フィルタチェーンを呼び出すことで、次のアクションが呼び出されます` などとなるかと思いますが、いかがでしょう。

2018-02-03 02:47 UTC, garbagetown commented on manual/working/scalaGuide/advanced/http/ScalaHttpFilters.md
> +`nextFilter` パラメータはフィルタチェーン内の次のアクションを表します。これを呼び出すとアクションが呼び出されます。ほとんどの場合、将来的にはいつでもこのメソッドを呼び出すことになります。なんらかの理由でリクエストをブロックしたい場合は、これを呼び出さないようにします。
`invoke this` の `this` は `nextFilter` パラメータでしょうか。
`you will probably want to` なので、直訳すると `ほとんどの場合、未来のある同じ時点でこのフィルタを起動することを望むでしょう` となり、意訳すると `未来のある同じ時点でこのフィルタを起動したい場合が多くあるでしょう` などとなるでしょうか。

2018-02-03 02:47 UTC, garbagetown commented on manual/working/scalaGuide/advanced/http/ScalaHttpFilters.md
> +`nextFilter` パラメータはフィルタチェーン内の次のアクションを表します。これを呼び出すとアクションが呼び出されます。ほとんどの場合、将来的にはいつでもこのメソッドを呼び出すことになります。なんらかの理由でリクエストをブロックしたい場合は、これを呼び出さないようにします。
`You may decide to not invoke` なので、直訳すると `呼び出さないと決意するかもしれない` でしょうか。
やや意訳し過ぎかもしれませんが、前の文の `want to invoke` との対比を意識すると `呼び出したくない場合があるかもしれません` くらいでも良いかと思います。

2018-02-03 02:47 UTC, garbagetown commented on manual/working/scalaGuide/advanced/http/ScalaHttpFilters.md
> +チェーン内で次のフィルタを呼び出す前にタイムスタンプを保持します。次のフィルタを呼び出すと、最終的に使用される `Future[Result]` が返されます。非同期レスポンスの詳細については、[[非同期レスポンスの処理|ScalaAsync]] の章を見てください。`Result` を持つクロージャを使って `map` メソッドを呼び出すことによって、`Future` 内の `Result`
API を見られていないのですが `a closure that takes a Result` なので、`Result を受け取るクロージャ` かなと思いました。

2018-02-03 02:47 UTC, garbagetown commented on manual/working/scalaGuide/advanced/http/ScalaHttpFilters.md
> +チェーン内で次のフィルタを呼び出す前にタイムスタンプを保持します。次のフィルタを呼び出すと、最終的に使用される `Future[Result]` が返されます。非同期レスポンスの詳細については、[[非同期レスポンスの処理|ScalaAsync]] の章を見てください。`Result` を持つクロージャを使って `map` メソッドを呼び出すことによって、`Future` 内の `Result`
細かいですが、`send it back to the client (snip), too` あるいは `also send it back to the client` のように強調されていないので、`も` は取ってしまって `レスポンスヘッダでクライアントに送信します` でよいと思います。

2018-02-03 02:47 UTC, garbagetown commented on manual/working/scalaGuide/advanced/http/ScalaHttpFilters.md
> +ここでの主な違いは、渡された `next` アクションをラップするための新しい `EssentialAction` を作成することとは別に、次に呼び出すときに `Iteratee` を返すことです。あなたが望むなら `Enumeratee` でこれを包み込み、いくつかの変換を行うことができます。iteratee の結果を `map` して処理します。
原文が難しい・・・というか口語的で文章として雑ですね ^^; `is when we invoke next,` の部分は `is when we invoke the next action,` じゃないのかなあ・・・
"ここでの主な違いは、あ、 next アクションに渡されたものをラップするために EssentialAction を新しく作っているのは置いといて。next アクションを呼び出した時に Iteratee が戻ってくることなんだ" のような内容かと。

従って `next アクションとして渡されたものをラップするために EssentialAction を新しく作成していることは別として、ここでの主な違いは next アクションを呼び出したときに Iteratee を受け取ることです` のようになるかと思いました。

2018-02-03 02:47 UTC, garbagetown commented on manual/working/scalaGuide/advanced/http/ScalaHttpFilters.md
> +ここでの主な違いは、渡された `next` アクションをラップするための新しい `EssentialAction` を作成することとは別に、次に呼び出すときに `Iteratee` を返すことです。あなたが望むなら `Enumeratee` でこれを包み込み、いくつかの変換を行うことができます。iteratee の結果を `map` して処理します。
`if you wished` を `もしあなたが望むなら` と訳すと少し大袈裟な印象がありました。`これを Enumeratee でラップしていくつかの変換を行うこともできます` 程度でも良いかもしれません。

2018-02-03 02:47 UTC, garbagetown commented on manual/working/scalaGuide/advanced/http/ScalaHttpFilters.md
> +ここでの主な違いは、渡された `next` アクションをラップするための新しい `EssentialAction` を作成することとは別に、次に呼び出すときに `Iteratee` を返すことです。あなたが望むなら `Enumeratee` でこれを包み込み、いくつかの変換を行うことができます。iteratee の結果を `map` して処理します。
`then` と `thus` のニュアンスが難しいですね。`it` は `result of iteratee` でしょうか。
直訳すると `(Enumeratee にラップした) その後 iteratee の結果を map して、それにより iteratee の結果を処理します` となり、意訳して `その後、iteratee の結果を map して処理します` でしょうか。
`then` のニュアンスだけ付け足して頂けますでしょうか。

2018-02-03 02:47 UTC, garbagetown commented on manual/working/scalaGuide/advanced/http/ScalaHttpFilters.md
> +> 2 つの異なるフィルタ API があるように見えるかもしれませんが、`EssentialFilter` は 1 つのみです。以前の例の、より簡単な `Filter` API は、`EssentialFilter` を継承し、新しい `EssentialAction` を作成することでそれを実装します。渡されたコールバックは、ボディ解析と残りのアクションが非同期に実行されている間、`Resul
`there is only one, EssentialFilter. ` は直訳すると `そこにあるのはただ一つ、EssentialFilter です` となりますが、やや大袈裟な感じになってしまうので `ただ 1 つ EssentialFilter があるだけです` などではいかがでしょうか。

2018-02-03 02:47 UTC, garbagetown commented on manual/working/scalaGuide/advanced/http/ScalaHttpFilters.md
> +> 2 つの異なるフィルタ API があるように見えるかもしれませんが、`EssentialFilter` は 1 つのみです。以前の例の、より簡単な `Filter` API は、`EssentialFilter` を継承し、新しい `EssentialAction` を作成することでそれを実装します。渡されたコールバックは、ボディ解析と残りのアクションが非同期に実行されている間、`Resul
`The passed in callback` は `The (next action which is passed) in callback` でしょうか。
`makes it appear to ~` は `〜しているように見せる` かと。
多少意訳して `コールバックに渡された次のアクションは、ボディの解析と残りのアクションが非同期に実行されている間、Result の promise を作ることでボディの解析をスキップするように見せます` でしょうか。

2018-02-03 02:47 UTC, garbagetown commented on manual/working/scalaGuide/advanced/http/ScalaHttpFilters.md
> +対照的に、[[アクション組成|ScalaActionsComposition]] は認証や認可、キャッシュなど、特定のルートに対する関心事を対象としています。もし、フィルターをすべてのルートに適用したいのでなければ、代わりにアクション組成の使用を検討してみてください。アクション組成はフィルターよりも遙かに強力です。また、定型的なコードを最小限にするために、ルート毎に独自の定義済みアクション群を構
うーん、これはどうなんでしょう。自分も Scala にあまり詳しくないのですが、関数型言語の文脈では composition は合成と訳されることが多い認識です。
自分が不勉強な場合は、合成という訳がしっくり来ない理由や、組成という訳が相応しい理由をご共有頂けるとうれしいです 🙇

2018-02-03 11:17 UTC, 12345 commented on manual/working/scalaGuide/advanced/http/ScalaHttpFilters.md
> +対照的に、[[アクション組成|ScalaActionsComposition]] は認証や認可、キャッシュなど、特定のルートに対する関心事を対象としています。もし、フィルターをすべてのルートに適用したいのでなければ、代わりにアクション組成の使用を検討してみてください。アクション組成はフィルターよりも遙かに強力です。また、定型的なコードを最小限にするために、ルート毎に独自の定義済みアクション群を構
`合成`という表現がしっくりこなかったのは、単に自分にとって馴染みが無かっただけです。こちらこそ不勉強で申し訳ありません。

2018-02-03 11:19 UTC, 12345 commented on manual/working/scalaGuide/advanced/http/ScalaHttpFilters.md
> +ここで何が起こっているのかを見てみましょう。最初に注文すべきは `apply` メソッドのシグネチャです。これはカリー化された関数で、最初のパラメータ `nextFilter` はリクエストヘッダを取得して結果を生成する関数で、次のパラメータ `requestHeader` は受信するリクエストの実際のリクエストヘッダです。
> 最初に注文すべきは は 最初に注目すべきは でしょうか？

typoですね、すみません。(カリーの話につられたのだろうか・・)

> カリー化された関数で、(snip)生成する関数で、 と 関数で がくり返されており少し気になりました。

文章を分けるやり方で修正しました！

2018-02-03 11:20 UTC, 12345 commented on manual/working/scalaGuide/advanced/http/ScalaHttpFilters.md
> +`nextFilter` パラメータはフィルタチェーン内の次のアクションを表します。これを呼び出すとアクションが呼び出されます。ほとんどの場合、将来的にはいつでもこのメソッドを呼び出すことになります。なんらかの理由でリクエストをブロックしたい場合は、これを呼び出さないようにします。
ご指摘の内容で修正しました！

2018-02-03 11:20 UTC, 12345 commented on manual/working/scalaGuide/advanced/http/ScalaHttpFilters.md
> +チェーン内で次のフィルタを呼び出す前にタイムスタンプを保持します。次のフィルタを呼び出すと、最終的に使用される `Future[Result]` が返されます。非同期レスポンスの詳細については、[[非同期レスポンスの処理|ScalaAsync]] の章を見てください。`Result` を持つクロージャを使って `map` メソッドを呼び出すことによって、`Future` 内の `Result`
ご指摘の内容で修正しました！

2018-02-03 11:20 UTC, 12345 commented on manual/working/scalaGuide/advanced/http/ScalaHttpFilters.md
> +ここでの主な違いは、渡された `next` アクションをラップするための新しい `EssentialAction` を作成することとは別に、次に呼び出すときに `Iteratee` を返すことです。あなたが望むなら `Enumeratee` でこれを包み込み、いくつかの変換を行うことができます。iteratee の結果を `map` して処理します。
ご指摘の内容で修正しました！

2018-02-03 11:20 UTC, 12345 commented on manual/working/scalaGuide/advanced/http/ScalaHttpFilters.md
> +> 2 つの異なるフィルタ API があるように見えるかもしれませんが、`EssentialFilter` は 1 つのみです。以前の例の、より簡単な `Filter` API は、`EssentialFilter` を継承し、新しい `EssentialAction` を作成することでそれを実装します。渡されたコールバックは、ボディ解析と残りのアクションが非同期に実行されている間、`Resul
ご指摘の内容で修正しました！

2018-02-03 11:22 UTC, 12345 commented
修正しました。お手数ですが再度ご確認をお願いします！:bow:

2018-02-06 21:54 UTC, garbagetown commented on manual/working/scalaGuide/advanced/http/ScalaHttpFilters.md
> +ここで何が起こっているのかを見てみましょう。最初に注文すべきは `apply` メソッドのシグネチャです。これはカリー化された関数で、最初のパラメータ `nextFilter` はリクエストヘッダを取得して結果を生成する関数で、次のパラメータ `requestHeader` は受信するリクエストの実際のリクエストヘッダです。
カリーを注文しちゃったんですねw

2018-02-06 21:56 UTC, garbagetown approved these changes

2018-02-06 21:56 UTC, merged

2018-02-06 21:56 UTC, garbagetown commented
ご対応ありがとうございます！